version: '3.5'
services:
  app-mvc:
    container_name: app-kanachsnund-mvc
    image: app-kanachsnund
    build: ./
    ports:
      - "80:80"
    depends_on:
      - dbpostgresql
    volumes:
      - app-image:/var/images
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=fjvedhf43672873ehjcbeg463487hcehvcgecje
      - POSTGRES_USER=postgres
      - POSTGRES_DB=kanachsnund
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
  app-image:
    driver: local