spring:
  datasource:
    username: postgres
    password: fjvedhf43672873ehjcbeg463487hcehvcgecje
    url: jdbc:postgresql://dbpostgresql:5432/kanachsnund
project:
  username: kanachsnund.marketing@gmail.com
  password: Kanachsnund-new-project
  images:
    product: /var/images
server:
  port: 80