spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/kanachsnund
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        generate_statistics: true
        jdbc:
          batch_size: 5
          batch_versioned_data: true
        order_updates: true
        order_inserts: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    change-log: classpath:db/migration.xml

project:
  username: admin
  password: admin
  images:
    product: D:\\images

server:
  error:
    whitelabel:
      enabled: false
    path: /error